-- Create user and database for E-Learning AI App
CREATE USER lap04 WITH ENCRYPTED PASSWORD 'lap04pass';
CREATE DATABASE mydb OWNER lap04;
GRANT ALL PRIVILEGES ON DATABASE mydb TO lap04;

-- Grant necessary privileges
ALTER USER lap04 CREATEDB;
\c mydb
GRANT ALL ON SCHEMA public TO lap04;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO lap04;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO lap04; 